# Generated by Django 5.1.3 on 2025-01-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_make_evaluee_fields_non_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="evaluee",
        ),
        migrations.RemoveField(
            model_name="medicalrequirement",
            name="care_plan",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="care_plan",
        ),
        migrations.CreateModel(
            name="CarePlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("physician_evaluation", "Physician Evaluation"),
                            ("physician_followup", "Physician Follow Up"),
                            ("diagnostics", "Diagnostics"),
                            ("medications", "Medications"),
                            ("therapy_evaluations", "Therapy Evaluations"),
                            ("therapies", "Therapies"),
                            ("interventional", "Interventional"),
                            ("surgeries", "Surgeries"),
                            ("aids_independence", "Aids for Independence"),
                            ("prosthetics_orthotics", "Prosthetics/Orthotics"),
                            ("supplies", "Supplies"),
                            ("home_services", "Home Services"),
                            ("home_maintenance", "Home Maintenance"),
                            ("home_modification", "Home Modification"),
                            ("case_management", "Case Management"),
                            ("transportation", "Transportation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("frequency", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "care_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.careplan",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "start_date"],
            },
        ),
        migrations.DeleteModel(
            name="CareTeamMember",
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
        migrations.DeleteModel(
            name="MedicalRequirement",
        ),
        migrations.DeleteModel(
            name="Treatment",
        ),
    ]
